[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solmmerce = "2AcCviVANT7SFU7hVhBL2rWZ5maCupvNEM6xFDuPi19n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nhuxhr/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit"
